theme: jekyll-theme-cayman

name: regiovision e.V.
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Über uns', link: '/about'}
  - {name: 'Kontakt', link: '/contact'}
